apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: systempc23/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: systempc23/client
      context: client
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./deployments/*
deploy:
  kubectl: {}